In [2]:
#set 不能有重複值，有的話會被刪掉。
set1:set = {1,1,3,3,5,8,7,9,10}
set1.add(11)
set1

{1, 3, 5, 7, 8, 9, 10, 11}

起動numpy
在終端機輸入：pip install numpy

In [10]:
import numpy as np
array1:np.ndarray=np.array(range(1,11))

#陣列運算
array1 +10*10


array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
#np.arange可以做到小數點跟陣列運算
#display 只能在jubyt環境使用
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))


array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [19]:
display(np.random.random())
#10組數值，每組5行3列的值
display(np.random.randn(10,5,3))

0.30654304353252604

array([[[ 3.40799452e-02,  1.07828090e+00, -8.44251371e-01],
        [-3.55839548e-01, -1.17817042e+00, -1.77902870e+00],
        [-9.35523298e-01, -2.60574053e-01, -8.35288326e-01],
        [-2.59826430e+00, -1.38041093e+00, -6.50462937e-01],
        [-4.88587359e-01,  2.71247623e-01,  2.02779057e+00]],

       [[ 9.91367841e-01,  1.19712952e+00, -1.83178888e-01],
        [-2.57760878e-01, -7.33108245e-01, -2.79178432e-01],
        [-2.11132689e+00,  8.95276464e-01,  5.89850268e-01],
        [ 9.45385641e-01, -9.57731594e-01, -7.15517399e-01],
        [ 1.07609193e+00,  2.62949156e-01, -3.21761774e-01]],

       [[-8.71952339e-01,  2.63527644e-01,  1.44679699e+00],
        [ 1.80251808e-01, -8.08340511e-01,  7.10372705e-02],
        [-1.16718269e+00,  7.16187689e-01, -1.02492409e+00],
        [-9.45483610e-01, -2.77650214e-01,  1.12137018e+00],
        [-1.24233842e+00,  1.14196545e+00, -2.19315514e-01]],

       [[ 1.23089767e+00,  5.34050200e-01, -1.40311569e+00],
        [ 2.390203