In [2]:
#set 不能有重複值，有的話會被刪掉。
set1:set = {1,1,3,3,5,8,7,9,10}
set1.add(11)
set1

{1, 3, 5, 7, 8, 9, 10, 11}

起動numpy
在終端機輸入：pip install numpy

In [10]:
import numpy as np
array1:np.ndarray=np.array(range(1,11))

#陣列運算
array1 +10*10


array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
#np.arange可以做到小數點跟陣列運算
#display 只能在jubyt環境使用
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))


array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [20]:
display(np.random.random())
#10組數值，每組5行3列的值
display(np.random.randn(10,5,3))
display(np.random.randint(1,10,size=(10,5)))

0.7921026812183614

array([[[ 6.47761891e-02, -1.10749975e-01, -7.91641726e-02],
        [ 1.49675174e-01, -7.90500411e-02, -1.98376637e-01],
        [-9.66691529e-03, -1.59114846e+00,  1.73694126e-01],
        [ 1.46299449e+00, -2.16902589e+00,  1.37005593e+00],
        [-1.28701743e+00,  1.72820153e+00, -1.01332196e+00]],

       [[ 8.99014644e-01,  2.58701415e+00, -3.93262833e-01],
        [ 4.13012001e-01,  1.34365989e+00,  2.91178311e+00],
        [ 7.31468659e-01, -1.13328914e+00, -2.29134579e+00],
        [ 6.41560688e-02, -2.61107708e-01, -9.76828027e-01],
        [-2.92897806e-01, -2.16553386e-01,  9.38990084e-01]],

       [[ 5.35791291e-01, -3.56159164e-01,  1.56779196e+00],
        [ 8.11863669e-01, -7.59361646e-02, -5.98857707e-01],
        [-4.86794441e-01,  6.97294528e-01,  1.14863842e-01],
        [-5.13713702e-01,  5.86515196e-01, -1.21470615e+00],
        [ 9.56176258e-01,  5.86389583e-01,  2.51696083e-01]],

       [[ 1.26502675e+00,  6.34355769e-01,  8.21665465e-01],
        [-7.226304

array([[2, 9, 1, 7, 9],
       [7, 1, 1, 6, 8],
       [9, 3, 3, 9, 9],
       [3, 8, 9, 8, 7],
       [3, 6, 3, 1, 9],
       [3, 2, 8, 1, 3],
       [2, 7, 9, 8, 6],
       [2, 7, 4, 2, 4],
       [2, 8, 2, 6, 9],
       [8, 9, 6, 3, 9]])

In [21]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-3,3,50)
display(x)
figure = plt.figure(figsize=(8,4))
axes = figure.add_subplot()
axes.plot(x)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'