In [2]:
#set 不能有重複值，有的話會被刪掉。
set1:set = {1,1,3,3,5,8,7,9,10}
set1.add(11)
set1

{1, 3, 5, 7, 8, 9, 10, 11}

起動numpy
在終端機輸入：pip install numpy

In [10]:
import numpy as np
array1:np.ndarray=np.array(range(1,11))

#陣列運算
array1 +10*10


array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
#np.arange可以做到小數點跟陣列運算
#display 只能在jubyt環境使用
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))


array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [26]:
display(np.random.random())
#10組數值，每組5行3列的值
display(np.random.randn(10,5,3))
display(np.random.randint(1,10,size=(10,5)))

0.07047407808261585

array([[[ 0.31160779, -0.18011955, -0.849198  ],
        [ 1.3639056 ,  0.97588005, -0.5093625 ],
        [ 0.41769312,  1.82094274,  0.09799457],
        [ 0.63685153,  0.9271351 ,  0.25179103],
        [-1.37538371, -3.51311052, -0.35170611]],

       [[-0.14693982,  0.9172826 , -2.1717086 ],
        [ 0.04300957,  2.11288938,  0.23077761],
        [ 0.09475928, -1.05225919, -1.28481366],
        [-0.01091737, -0.37812426,  0.59185006],
        [ 1.57819497,  0.65930131, -2.50028584]],

       [[ 0.33077971, -0.53665678,  0.82246052],
        [ 0.80086437, -0.40358044,  0.46158567],
        [ 1.22169311,  0.40461989, -1.44296436],
        [ 1.23096183, -1.05245493,  1.79090483],
        [-0.46971426,  0.357065  , -0.37297166]],

       [[-2.42939426,  0.75869375, -0.02757766],
        [ 2.17321706, -1.32751112, -0.1417364 ],
        [-1.14572706,  1.23125121,  0.8362762 ],
        [ 0.73047733, -1.20451509,  1.05689799],
        [ 0.79721249,  0.17661581, -1.39959178]],

       [[ 1.

array([[2, 2, 2, 4, 2],
       [3, 5, 9, 9, 9],
       [5, 7, 7, 2, 8],
       [4, 1, 6, 9, 3],
       [9, 4, 2, 3, 5],
       [7, 5, 7, 8, 6],
       [8, 8, 7, 9, 4],
       [6, 6, 8, 2, 5],
       [7, 1, 3, 1, 2],
       [4, 3, 1, 4, 8]])

In [22]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-3,3,50)
display(x)
figure = plt.figure(figsize=(8,4))
axes = figure.add_subplot()
axes.plot(x)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'